language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=MYSQL CORE_RELEASE=3.4

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL CORE_RELEASE=3.6 COVERAGE="--coverage-clover=coverage.xml"
    - php: 7.1
      env: DB=PGSQL CORE_RELEASE=3

before_script:
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit "$COVERAGE" ideannotator/tests

# Share coverage results with codecov.io
after_success:
  - >
    test "$COVERAGE" != ""
    && mv coverage.xml ~/build/$TRAVIS_REPO_SLUG
    && cd ~/build/$TRAVIS_REPO_SLUG
    && bash <(curl -s https://codecov.io/bash)
