# See https://github.com/silverstripe/silverstripe-travis-support for setup details

sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - DB=MYSQL CORE_RELEASE=4@dev

before_script:
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit ideannotator/tests

after_success:
  - cd ~/builds/ss/ideannotator
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml
