# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: brettt89/silverstripe-web
        environment:
          - SS_DATABASE_CLASS=MySQLPDODatabase
          - SS_DATABASE_SERVER=127.0.0.1
          - SS_DATABASE_USERNAME=root
          - SS_DATABASE_PASSWORD=ubuntu
          - SS_DATABASE_NAME=circle_test
          - SS_ENVIRONMENT_TYPE=dev
          - JWT_PREFIX=jwt_
          - JWT_SIGNER_KEY=test_signer
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_DATABASE=circle_test
          - MYSQL_HOST=127.0.0.1

    working_directory: ~/var/www

    steps:
      # Install additional requirements
      - run:
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
            php -r "unlink('composer-setup.php');"

      - run: composer create-project silverstripe/installer:dev-master ~/var/www -n
      - run: git clone -b 3 https://github.com/silverleague/silverstripe-ideannotator ideannotator
      - run: cp ideannotator/tests/composer.test.json ./composer.json
      - run: composer update
      - run: rm phpunit.xml.dist
      - run: cp ideannotator/phpunit.xml.dist .
      - run: vendor/silverstripe/framework/sake dev/build flush=1 skipannotations=true

      # run tests!
      - run: vendor/bin/phpunit ideannotator/tests -d memory_limit=512M
