---
Name: ideannotator
Before:
  - 'mysite/*'
After:
  - 'framework/*'
  - 'cms/*'
---
SilverStripe\Dev\DevBuildController:
  extensions:
    - Axyr\IDEAnnotator\Annotatable
Axyr\IDEAnnotator\DataObjectAnnotator:
    enabled_modules:
      - mysite
