---
Name: ideannotator
---
SilverStripe\Dev\DevBuildController:
  extensions:
    - SilverLeague\IDEAnnotator\Annotatable
SilverLeague\IDEAnnotator\DataObjectAnnotator:
    enabled_modules:
      - mysite
